blank_issues_enabled: false
contact_links:
  - name: Customer support
    url: https://www.abcxyz.com/support
    about: Use this for subscription/license/module access questions.
  - name: Security issues
    url: https://github.com/abcxyz/terraform-aws-observability-pro/security/policy
    about: Please report vulnerabilities via the SECURITY policy.
