name: ClusterFuzzLite cron tasks

on:
  schedule:
    - cron: '0 0 * * *'  # daily at midnight UTC (change if you want)
  workflow_dispatch:

permissions: read-all

jobs:
  Pruning:
    runs-on: ubuntu-latest
    steps:
      - name: Build Fuzzers
        id: build
        uses: google/clusterfuzzlite/actions/build_fuzzers@884713a6c30a92e5e8544c39945cd7cb630abcd1
        with:
          language: go
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Run Fuzzers (prune)
        id: run
        uses: google/clusterfuzzlite/actions/run_fuzzers@884713a6c30a92e5e8544c39945cd7cb630abcd1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          fuzz-seconds: 300
          mode: 'prune'
          output-sarif: true

  # Optional: periodic coverage reports
  # Coverage:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Build Fuzzers (coverage)
  #       id: build
  #       uses: google/clusterfuzzlite/actions/build_fuzzers@v1
  #       with:
  #         language: go
  #         github-token: ${{ secrets.GITHUB_TOKEN }}
  #         sanitizer: coverage
  #
  #     - name: Run Fuzzers (coverage)
  #       id: run
  #       uses: google/clusterfuzzlite/actions/run_fuzzers@v1
  #       with:
  #         github-token: ${{ secrets.GITHUB_TOKEN }}
  #         fuzz-seconds: 600
  #         mode: 'coverage'
  #         sanitizer: 'coverage'
