name: fuzz

on:
  pull_request:
  schedule:
    - cron: "0 2 * * 0"  # weekly
  workflow_dispatch:

permissions:
  contents: read

jobs:
  go-fuzz:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1
      - uses: actions/setup-go@7a3fe6cf4cb3a834922a1244abfce67bcef6a0c5
        with:
          go-version: "1.22"
      - name: Run fuzzing (short)
        run: |
          go test ./fuzz -run=^$ -fuzz=FuzzHCLParse -fuzztime=30s
